# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Py Code


on:
  push:
    branches:
      - main
    
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t my-ai-model .

    - name: run docker
      run: docker run -d -p 8088:3000 --name test-container my-ai-model

    # - name: Push Docker image
    #   run: |
    #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    #     docker tag my-ai-model:latest ${{ secrets.DOCKER_USERNAME }}/ai-test:ai-image
    #     docker push ${{ secrets.DOCKER_USERNAME }}/ai-test:ai-image

    # - name: Pull Image
    #   run: docker pull bobsayshi/ai-test:ai-image
      
    # - name: Run Container
    #   run: docker run -p 8080:80 bobsayshi/ai-test:ai-image

    # - name: Verify Container Running
    #   run: docker ps




